### ISSUE TITLE
Insert bulletpoints when new line is added via o/O in lists

### ISSUE THREAD

**Issue by schickling** [plasticboy/vim-markdown#139]
When I'm adding a new line with the keys `o` or `O` I would expect the same behavior as described here https://github.com/plasticboy/vim-markdown/pull/36

Currently it looks like this: 

![screenshot 2014-11-01 13 57 40](https://cloud.githubusercontent.com/assets/1567498/4871759/b233be2a-61c6-11e4-884a-4a8ba11ae6e1.png)

**Comment by tbastos** [comment]
This issue makes the plugin unusable for me. I have to write bulleted lists all the time, and currently this plugin makes it a huge struggle:
- It increases the indentation every time I hit enter (99% of the time I want to create a bulleted list, not a bulleted tree... extremely annoying and time wasting).
- It doesn't add a bullet at the beginning of line (not as annoying, but it's something I would expect)

Honestly, I can't see the rationale why these are not the default. BTW for me hitting 'o' in normal mode has the same behavior as hitting enter in insert mode, not sure if it was ever different.

**Comment by simplyianm** [comment]
agree

**Comment by shirosaki** [comment]
Now indent size is configurable.
https://github.com/plasticboy/vim-markdown#adjust-new-list-item-indent

**Comment by joaqo** [comment]
@schickling sorry to revive this issue, but the issue is not exactly resolved atm imo.

Setting `let g:vim_markdown_new_list_item_indent = 0` fixes the problem of having `o` and `pressing Enter in insert mode` behaving differently with respect to the indentation they set, but it doesn't fix the problem of `pressing Enter in insert mode` inserting a bullet point in the new line (expected behaviour) and `o` not doing so (unexpected behaviour).

I think most, if not all, of vim's indentation plugins behave exactly the same when pressing enter in insert mode and when pressing `o` in normal mode, so I don't think vim-markdown should be the exception to the rule here.

Thanks for the great project, cheers!
