### ISSUE TITLE
YAML code blocks confuse syntax highlighting

### ISSUE THREAD

**Issue by sruggier** [plasticboy/vim-markdown#187]
See the attached screenshot for more detail:
![issue](https://cloud.githubusercontent.com/assets/427071/6932440/50492384-d7e7-11e4-9480-64ef4aedb5da.png)

I don't have vim_markdown_frontmatter defined, so this issue would appear to be unrelated to that feature, oddly enough.

**Comment by cirosantilli** [comment]
@sruggier thanks for the issue. Next time, please:

- try to produce a minimal test case
- also give us the bad input as text instead of just the image

By creating a minimal example, I was able to see that this is not related to the YAML, but rather to the evil Setex headers, so I'm closing this in favor of: https://github.com/plasticboy/vim-markdown/issues/189

**Comment by sruggier** [comment]
Thanks for taking the time to reproduce this! If I file any more bugs, I'll keep these two things in mind.
