### ISSUE TITLE
Rewrapping a bullet point inserts new bullet points

### ISSUE THREAD

**Issue by jefferai** [plasticboy/vim-markdown#232]
I had a very long line starting with a bullet point. Without `vim-markdown`, selecting the text and rewrapping it via `gq` (to fit in 80 columns) causes the text to be wrapped mostly as expected (with some slight formatting glitches).

With `vim-markdown` installed, each of these new lines was preceded with an asterisk, causing each wrapped line to be an individual bullet point.

**Comment by jefferai** [comment]
Strange. I tried it again after first wrapping the text without vim-markdown; in this case, vim-markdown correctly formatted it and did not add any new bullet points.

**Comment by jefferai** [comment]
I played around with this some more; it seems like when rewrapping text that is already multi-line, it does the correct thing. However, if the text you want to wrap is currently a single long line, it turns each new line into a bullet point.

**Comment by cirosantilli** [comment]
Please provide a minimal on the issue description so we an understand it faster ;-)

**Comment by jefferai** [comment]
I'm not sure how to be clearer than I was. Make a long line starting with a bullet point:
```
* This is a long line that is preceded by an asterisk, e.g. a Markdown bullet point. When I wrap it bad things will happen.
```
Wrap it with vim-markdown installed:
```
* This is a long line that is preceded by an asterisk, e.g. a Markdown bullet
* point. When I wrap it bad things will happen.
```
Now you have two bullet points.

**Comment by tomxtobin** [comment]
Just ran into this; it only gets triggered when `formatoptions` includes `q`.

**Comment by timon** [comment]
When `formatoptions` includes `t` and `textwidth` is set, this happens each time VIM breaks long line.

**Comment by lemontheme** [comment]
After a lot of trial and error, I was able to fix this by adding the following to my *.vimrc*.

```
autocmd FileType markdown 
    \ set formatoptions-=q |
    \ set formatlistpat=^\\s*\\d\\+\\.\\s\\+\\\|^\\s*\[-*+]\\s\\+
```

Explanation:

1. As @tomxtobin explains, `q` is a confusing factor,  causing Vim to misidentify Markdown bullets as comment markers. So start by removing that.
2. Markdown bullets *are* covered by `formatlistpat`, but – whether intentional or not – the current regex does allow for these bullets to be indented. Prefixing this part of `formatlistpat` with `^\\s*` seems to have fixed that. 

Disclaimer: I'm still relatively new to Vim. Just wanted to share this in case I'm not the only who one found this something of a deal-breaker.

**Comment by andmatand** [comment]
lemontheme's solution does not seem to work for me; in fact, even just having`set formatoptions-=q` present makes the next line's indentation too big, like this:
```
* This is a line and then when I use gq it
    wraps like this
```
This is in vim 8.0...maybe something has changed in the new version to cause this to no longer work?

**Comment by anowlcalledjosh** [comment]
I think the `comments` option might be the root cause of this. I'm using Vim 8.1.20, and `comments` is set to `b:*,b:+,b:-,b:>` – removing the first three elements from that by setting it to just `b:>` seems to solve this issue, and avoids the extra indentation that @andmatand mentioned.

**Comment by anowlcalledjosh** [comment]
Turns out this issue was even noted in [the buggy commit](https://github.com/plasticboy/vim-markdown/commit/642730fccce7e78c995389f3c430747d266efa96#diff-1a30951b497d8c982372cc7397d96168R13) itself...

The basic problem is that the `*`, `-` and `+` characters are being treated like comment characters, but they are *not* used like comment characters. The feature is, afaik, intended for this style of comment:

```c
/* asdf
 * some text
 * some more text
 */
```

but it's being misused for bulleted lists, which look something like this:

```markdown
- foo bar
- some extreeeeeeeeeeeeeemely long text that
  is so long that it wraps
- some more text
```

Note that, in the code comment, *every* line starts with ` * ` and when Vim rewraps the comment, it should automatically insert and remove them as needed. But in the Markdown case, only some lines start with `- ` and Vim should never insert or remove bullets automatically when rewrapping.

**Comment by dylan-chong** [comment]
@shirosaki This is still a problem! (see @anowlcalledjosh 's link) Will this get fixed anytime? This problem is very annoying!
