### ISSUE TITLE
Would you allow the :Toc quickfix window to toggle

### ISSUE THREAD

**Issue by CoinCheung** [plasticboy/vim-markdown#356]
I find the feature of :Toc is very useful, as it does with tagbar. However, tagbar allows to toggle the quickfix window which is quite convenient, would you add some features like this?

**Comment by khughitt** [comment]
Also think having something like `:TocToggle` (or just have a second call to `:Toc` toggle its visibility, if already open) would be really nice.

**Comment by AleCandido** [comment]
I know that this issue is quite old, but I don't feel enough confident to make a pull request and I would like to have opinion and improvements on my attempt solution.

What I'm currently using is:
```vim
" ~/.vim/ftplugin/markdown.vim

function s:TocToggle()
    if index(["markdown", "qf"], &filetype) == -1
        return
    endif

    if get(getloclist(0, {'winid':0}), 'winid', 0)
        " the location window is open
        lclose
    else
        " the location window is closed
        Toc
    endif
endfunction

command TocToggle call s:TocToggle()
```

- the first part of the function is just checking the `filetype`
  - if **not checking** at all the command will output an horrible error if called on wrong buffers (not markdown ones), and this can happen frequently if you use the command through some kind of mapping
  - otherwise the **command** can be defined **locally to the buffer** with `command -buffer TocToggle call s:TocToggle()`, but in this case you need always to switch to the main window (the `.md` file) in order to have the command available, and it is quite uncomfartable
- the second part is the actual one: is checking if `quickfix` window is open or not, in the first case it closes the toc with `lclose`, otherwise it opens that with `Toc`.

**Comment by CoinCheung** [comment]
Thanks for replying, I am closing this.

**Comment by AleCandido** [comment]
Is it working for you?

**Comment by willchao612** [comment]
> I know that this issue is quite old, but I don't feel enough confident to make a pull request and I would like to have opinion and improvements on my attempt solution.
> 
> What I'm currently using is:
> 
> ```viml
> " ~/.vim/ftplugin/markdown.vim
> 
> function s:TocToggle()
>     if index(["markdown", "qf"], &filetype) == -1
>         return
>     endif
> 
>     if get(getloclist(0, {'winid':0}), 'winid', 0)
>         " the location window is open
>         lclose
>     else
>         " the location window is closed
>         Toc
>     endif
> endfunction
> 
> command TocToggle call s:TocToggle()
> ```
> 
> * the first part of the function is just checking the `filetype`
>   
>   * if **not checking** at all the command will output an horrible error if called on wrong buffers (not markdown ones), and this can happen frequently if you use the command through some kind of mapping
>   * otherwise the **command** can be defined **locally to the buffer** with `command -buffer TocToggle call s:TocToggle()`, but in this case you need always to switch to the main window (the `.md` file) in order to have the command available, and it is quite uncomfartable
> * the second part is the actual one: is checking if `quickfix` window is open or not, in the first case it closes the toc with `lclose`, otherwise it opens that with `Toc`.

Thanks Bruh, this works like a charm.

**Comment by marhop** [comment]
@AleCandido Just found this, works great. Would you consider making a pull request? It would be nice to have that feature out of the box, so I need less config. ;-)

**Comment by AleCandido** [comment]
Unfortunately, I'm not using this plugin any longer (so I'm not very interested). But feel free to take the code and author the PR yourself :)
