### ISSUE TITLE
markdown autolinking

### ISSUE THREAD

**Issue by iandstanley** [plasticboy/vim-markdown#505]
I'm seeing some behaviour when I edit markdown files but I am unsure if the behaviour is down to this plugin or vimwiki

When I accidentally hit enter over a word in command mode (thinking I'm in insert mode) it creates a markdown link.

If this is this plugin - how can I disable this bahaviour - or remap the key binding to say C-Enter ?

**Comment by fprawits** [comment]
This behaviour is caused by the vimwiki plugin. You can type `:map <CR>` inside your vim session to see what enter has been mapped to. This should default to `<Plug>VimwikiFollowLink` with a leading `@` highlighting a buffer local mapping.

To remove this mapping temporarily, try `:unmap <buffer> <CR>`
Tto make the change permanent, it is best to add the line `unmap <buffer> <CR>` to your filetype plugins, where filetype is either `vimwiki` or `markdown` depending on the syntax you are using vimwiki with.
